services:
  # 1. Web Server (PHP + Apache) -> Pengganti Apache & PHP di XAMPP
  web:
    image: php:8.2-apache
    container_name: per1_php_apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - web-network

  # 2. Database Server (MySQL) -> Pengganti MySQL di XAMPP
  db:
    image: mysql:8.0
    container_name: per1_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_database
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - web-network

  # 3. Database GUI (phpMyAdmin) -> Pengganti phpMyAdmin di XAMPP
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: per1_phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - web-network

networks:
  web-network:
    driver: bridge

volumes:
  db_data:
